dtb-$(CONFIG_ARCH_QCOM)	+= apq8016-sbc.dtb msm8916-mtp.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8996-mtp.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= apq8096-db820c.dtb

dtb-$(CONFIG_ARCH_SDM845) += sdm845-sim.dtb \
	sdm845-rumi.dtb \
	sdm845-v2-rumi.dtb \
	sdm845-v2-qvr-evt.dtb \
	sdm845-v2-qvr-dvt.dtb \
	sdm850-v2.1-w737.dtb

dtb-$(CONFIG_ARCH_SDM670) += sdm670-rumi.dtb \
	sdm670-mtp.dtb \
	sdm670-cdp.dtb \
	sdm670-qrd.dtb \
	sdm670-qrd-sku2.dtb \
	sdm670-pm660a-mtp.dtb \
	sdm670-pm660a-cdp.dtb \
	sdm670-external-codec-cdp.dtb \
	sdm670-external-codec-mtp.dtb \
	sdm670-external-codec-pm660a-cdp.dtb \
	sdm670-external-codec-pm660a-mtp.dtb \
	sdm670-usbc-cdp.dtb \
	sdm670-usbc-external-codec-cdp.dtb \
	sdm670-usbc-external-codec-mtp.dtb \
	sdm670-usbc-external-codec-pm660a-cdp.dtb \
	sdm670-usbc-external-codec-pm660a-mtp.dtb \
	sdm670-usbc-mtp.dtb \
	sdm670-usbc-pm660a-cdp.dtb \
	sdm670-usbc-pm660a-mtp.dtb \
	sda670-mtp.dtb \
	sda670-hdk.dtb \
	sda670-cdp.dtb \
	sdm670-tasha-codec-cdp.dtb \
	sdm670-pm660a-tasha-codec-cdp.dtb \
	sda670-pm660a-mtp.dtb \
	sda670-pm660a-cdp.dtb \
	sxr1120-lc-mtp.dtb \
	sxr1120-lc-external-codec-mtp.dtb \
	sxr1120-lc-cdp.dtb \
	sxr1120-lc-external-codec-cdp.dtb \
	qcs605-360camera.dtb \
	qcs605-mtp.dtb \
	qcs605-cdp.dtb \
	qcs605-external-codec-mtp.dtb \
	qcs605-lc-ipcamera.dtb \
	qcs605-lc-mtp.dtb \
	qcs605-lc-cdp.dtb \
	qcs605-lc-mtp-no-hdcp.dtb \
	sdm710-mtp.dtb \
	sdm710-cdp.dtb \
	sdm710-qrd.dtb \
	sdm710-qrd-sku2.dtb \
	sdm710-pm660a-mtp.dtb \
	sdm710-pm660a-cdp.dtb \
	sdm710-external-codec-cdp.dtb \
	sdm710-external-codec-mtp.dtb \
	sdm710-external-codec-pm660a-cdp.dtb \
	sdm710-external-codec-pm660a-mtp.dtb \
	sdm710-usbc-cdp.dtb \
	sdm710-usbc-external-codec-cdp.dtb \
	sdm710-usbc-external-codec-mtp.dtb \
	sdm710-usbc-external-codec-pm660a-cdp.dtb \
	sdm710-usbc-external-codec-pm660a-mtp.dtb \
	sdm710-usbc-mtp.dtb \
	sdm710-usbc-pm660a-cdp.dtb \
	sdm710-usbc-pm660a-mtp.dtb \
	sdm710-tasha-codec-cdp.dtb \
	sdm710-pm660a-tasha-codec-cdp.dtb \
	sxr1130-cdp.dtb \
	sxr1130-external-codec-cdp.dtb \
	sxr1130-mtp.dtb \
	sxr1130-external-codec-mtp.dtb \
	sxr1130-external-codec-pm660a-mtp.dtb \
	sxr1130-pm660a-mtp.dtb \
	sxr1130-usbc-external-codec-cdp.dtb \
	sxr1130-usbc-external-codec-mtp.dtb \
	sxr1130-usbc-external-codec-pm660a-mtp.dtb \
	sxr1130-usbc-mtp.dtb \
	sxr1130-usbc-pm660a-mtp.dtb \
	sxr1130-qrd.dtb \
	sxr1130-svr.dtb

dtb-$(CONFIG_ARCH_SDM845_VM) += sdm845-vm.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
